from .gat import GAT
from .gcn import GCN
from .graphconvnet import GraphConvNet
from .graphsage import GraphSAGE
from .appnp import APPNPNet
from .arma import ARMA
from .gatedgraph import GatedGraphNet
from .gin import GIN
from .sg import SG
from .tag import TAG
from .incepgcn import IncepGCN
from .resgcn import ResGCN
from .jkgcn import JKGCN
