from model_lib import *

class ModelSpace:
    """
    Model space which contains all the base models in model_lib
    Parameters:
    ----------
    info: dict
        The eda infomation generated by AutoEDA
    ----------
    """
    def __init__(self, info):
        self.info = info

        self.model_prior = self.info['chosen_models']

        self.model_lib = {
            'GraphConvNet': GraphConvNet,
            'GraphSAGE': GraphSAGE,
            'GAT': GAT,
            'GCN': GCN,
            'APPNP': APPNPNet,
            'ARMA': ARMA,
            'GatedGraph': GatedGraphNet,
            'GIN': GIN,
            'SG': SG,
            'TAG': TAG,
            'IncepGCN': IncepGCN,
            'ResGCN': ResGCN,
            'JKGCN': JKGCN
        }

    def get_models(self):
        ret = {}
        for model_name in self.model_prior:
            ret[model_name] = self.model_lib[model_name](self.info)
        return ret
